config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  ActiveAdmin.routes(self)

  # Routes for ActiveAdmin
  namespace :admin do
    resources :courses do
      resources :course_instances
    end
    resources :programs do
      resources :course_instances
    end
    resources :course_instances do
      resources :assignments
      resources :enrollments
    end
    resources :assignments do
      resources :rubrics
    end
    resources :submission_grades do
      resources :graded_rubrics
    end
  end

  # Routes for submit and grade students' solution
  resources :submission_grades, only: %i[show index]
  resources :graded_rubrics, only: %i[new show]
  
  # Custom routes
  root to: 'home#index'
  get 'active_assignments', to: 'assignments#active_assignments'
  get 'assigned_submissions', to: 'submission_grades#assigned_submissions'
  get 'submit_solution', to: 'submission_grades#new_solution', as: :new_solution
  post 'submission_grades', to: 'submission_grades#create', as: :submit_solution
  post 'submission_grades/:id', to: 'submission_grades#report_invalid', as: :report_invalid_submission
  get 'grade_form', to: 'submission_grades#grade_form', as: :grade_form
  post 'pre_caculate_grade', to: 'submission_grades#pre_caculate_grade', as: :pre_caculate_grade
  post 'grade_submission', to: 'submission_grades#grade', as: :grade_submission
  get 'graded_rubrics/preview', to: 'graded_rubrics#preview_get', as: :get_preview_rubric
  post 'graded_rubrics/preview', to: 'graded_rubrics#preview', as: :preview_rubric
  post 'graded_rubrics/pre_caculate', to: 'graded_rubrics#pre_caculate', as: :pre_caculate_rubric
  post 'graded_rubrics', to: 'graded_rubrics#grade', as: :grade_rubric
  post 'import_enrollments', to: 'enrollments#import_enrollments', as: :import_enrollments
  post 'reset_results', to: 'enrollments#reset_results', as: :reset_results
end

app/models/graded_rubric.rb
# frozen_string_literal: true

class GradedRubric < ApplicationRecord
  acts_as_paranoid
  belongs_to :submission_grade
  has_many :graded_criteriums, dependent: :destroy
  accepts_nested_attributes_for :graded_criteriums
  has_paper_trail on: %i[create update destroy]

  validates :comment, presence: true

  def display_name
    "Graded rubric of #{submission_grade.nil? ? '' : submission_grade.display_name}"
  end

  def status
    graded_criteriums.each do |criterium|
      next unless criterium.mandatory
      if criterium.criteria_type == Constants::CRITERIA_TYPE_PASS_FAIL
        if criterium.status == Constants::GRADED_CRITERIA_STATUS_FAILED
          return Constants::GRADED_RUBRIC_STATUS_FAILED
        end
      else # criteria_type = Constants::CRITERIA_TYPE_POINT
        if criterium.point.zero?
          return Constants::GRADED_RUBRIC_STATUS_FAILED
        end
      end
      Constants::GRADED_CRITERIA_STATUS_PASSED
    end
  end

  def calculate_point!
    temp_point = 0.to_f
    graded_criteriums.each do |criterium|
      if criterium.criteria_type == Constants::CRITERIA_TYPE_PASS_FAIL
        if criterium.status == Constants::GRADED_CRITERIA_STATUS_PASSED
          temp_point += (Settings[:criteria][:pass_fail_point] * criterium.weight).to_f / (submission_grade.assignment.rubric.total_weight).to_f
        end
      elsif criterium.criteria_type == Constants::CRITERIA_TYPE_POINT
        temp_point += ((criterium.point.to_f / (Settings[:criteria][:point_max_point]).to_f) * criterium.weight).to_f / (submission_grade.assignment.rubric.total_weight).to_f
      end
    end

    temp_point *= Settings[:submission][:point_factor]
    temp_point /= (2**(submission_grade.attempt-1)) if submission_grade.attempt != 1
    self.point = temp_point.round(2)
  end
end

app/controllers/graded_rubrics_controller.rb
# frozen_string_literal: true

class GradedRubricsController < ApplicationController
  before_action :set_graded_rubric, only: %i[show]

  def new
    # GradedRubricService.new.new_grade new_grade_params
    if params[:assignment_id].present? && params[:student_id].present? && params[:submission_grade_id]
      assignment_id = params[:assignment_id]
      student_id = params[:student_id]
      submission_grade_id = params[:submission_grade_id]
      submission_grades = SubmissionGrade.select(['id']).where(assignment_id: assignment_id,
                                                               student_id: student_id)
      graded_rubric = GradedRubric.select(['id']).where(submission_grade_id: submission_grades)
      graded_criteriums = GradedCriterium.where(graded_rubric_id: graded_rubric)
      @can_not_be_regrade_criteriums = graded_criteriums.reject(&:can_be_regrade?)
      can_not_be_regrade_index = @can_not_be_regrade_criteriums.map {|criterium| criterium.index}
      rubrics = Rubric.select(['id']).where(assignment_id: assignment_id)
      criteria_formats = CriteriaFormat.where(rubric_id: rubrics)
      @to_be_grade_criteria_formats = criteria_formats.reject {|criteria| can_not_be_regrade_index.include?(criteria.index)}

      @graded_rubric = GradedRubric.new(submission_grade_id: submission_grade_id)
      # Build graded_criteriums
      @to_be_grade_criteria_formats.each do |criteria|
        @graded_rubric.graded_criteriums.build(index: criteria.index,
                                               criteria_description: criteria.criteria_description,
                                               outcome: criteria.outcome,
                                               meet_the_specification: criteria.meet_the_specification,
                                               mandatory: criteria.mandatory,
                                               criteria_type: criteria.criteria_type,
                                               weight: criteria.weight)
      end
    else
      redirect_to root_path
    end
  end

  def pre_caculate
    result = GradedRubricService.new.pre_caculate_rubric pre_caculate_params

    respond_to do |format|
      format.html { render 'confirmation'}
      format.js {render js: 'comfirmation', :locals => {result: result}}
    end
  end

  def preview_get
    redirect_to root_path
  end

  def preview
    @graded_rubric = GradedRubric.new(graded_rubric_params)
    render :preview
  end

  def show;
  end

  def grade
    GradedRubricService.new.grade(graded_rubric_params)
    # @graded_rubric = GradedRubric.new(graded_rubric_params)
    # @graded_rubric.calculate_point!
    # submission_grade = @graded_rubric.submission_grade
    # if @graded_rubric.status == Constants::GRADED_RUBRIC_STATUS_FAILED
    #   submission_grade.status = Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED
    # else
    #   submission_grade.status = Constants::SUBMISSION_GRADE_STATUS_PASSED
    # end
    # submission_grade.update_point(@graded_rubric.point)
    # submission_grade.graded_at = Time.now

    # if @graded_rubric.save
    #   if submission_grade.save
    #     SubmissionGradeMailer.graded_email(submission_grade.id).deliver_later
    #     redirect_to @graded_rubric.submission_grade,
    #       success: 'Graded successfully!'

    #   end
    # end
  end

  private

  def set_graded_rubric
    @graded_rubric = GradedRubric.find(params[:id])
  end

  def graded_rubric_params
    params.require(:graded_rubric).permit(:submission_grade_id,
                                          :comment,
                                          graded_criteriums_attributes:
                                          %i[id index weight mandatory
                                             criteria_description outcome meet_the_specification
                                             criteria_type status point comment])
  end

  def new_grade_params
    params.permit(:assignment_id, :student_id, :submission_grade_id)
  end

  def pre_caculate_params
    params.require(:graded_rubric).permit(:submission_grade_id,
                                          :comment,
                                          graded_criteriums_attributes:
                                          %i[id index weight mandatory
                                             criteria_description outcome meet_the_specification
                                             criteria_type status point comment])

  end
end

app/helpers/graded_rubrics_helper.rb
# frozen_string_literal: true

module GradedRubricsHelper
  def pre_calculate_point(graded_rubric)
    point = 0.to_f

    graded_rubric.graded_criteriums.each do |criterium|
      if criterium.criteria_type == Constants::CRITERIA_TYPE_PASS_FAIL
        if criterium.status == Constants::GRADED_CRITERIA_STATUS_PASSED
          point += (Settings[:criteria][:pass_fail_point] * criterium.weight).to_f / (graded_rubric.submission_grade.assignment.rubric.total_weight).to_f
        end
      elsif criterium.criteria_type == Constants::CRITERIA_TYPE_POINT
        point += ((criterium.point.to_f / (Settings[:criteria][:point_max_point]).to_f) * criterium.weight).to_f / (graded_rubric.submission_grade.assignment.rubric.total_weight).to_f
      end
    end

    point *= Settings[:submission][:point_factor]

    if graded_rubric.submission_grade.attempt != 1
      point /= (2**(graded_rubric.submission_grade.attempt-1))
      prev_attempt = SubmissionGrade.where(assignment_id: graded_rubric.submission_grade.assignment_id,
                                           student_id: graded_rubric.submission_grade.student_id,
                                           attempt: graded_rubric.submission_grade.attempt - 1).first
      point += prev_attempt.point
    end
    point.round(2)
  end

  def pre_calculate_status(graded_rubric)
    temp_status = Constants::SUBMISSION_GRADE_STATUS_PASSED
    graded_rubric.graded_criteriums.each do |criterium|
      next unless criterium.mandatory
      if criterium.criteria_type == Constants::CRITERIA_TYPE_PASS_FAIL
        if criterium.status == Constants::GRADED_CRITERIA_STATUS_FAILED
          temp_status = Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED
        end
      else #Constants::CRITERIA_TYPE_POINT
        if criterium.point.zero?
          temp_status = Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED
        end
      end
    end
    temp_status
  end
end

app/views/graded_rubrics/form/_graded.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t('assignment.submission_grade.label.weight') %></th>
      <th style="width: 30%;"><%= t('assignment.submission_grade.label.meet_the_specification') %></th>
      <th><%= t('assignment.submission_grade.label.point') %></th>
      <th style="width: 20%;"><%= t('assignment.submission_grade.label.comment') %></th>
      <th><%= t('assignment.submission_grade.label.mandatory') %></th>
    </tr>
  </thead>
  <tbody>
    <% can_not_be_regrade_criteriums.each do |criteria| %>
      <tr>
        <th><%= criteria.index %></th>
        <td><span><%= criteria.weight %></span></td>
        <td><span><%= criteria.meet_the_specification %></span></td>
        <td>
          <%= render :partial => "graded_criteriums/status", :locals => {cr_type: criteria.criteria_type, cr_status: criteria.status, cr_point: criteria.point} %>
        </td>
        <td><span><%= criteria.comment %></span></td>
        <td>
          <%= render :partial => "graded_criteriums/mandatory", :locals => {mandatory: criteria.mandatory} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/graded_rubrics/form/_new.html.erb
<h4><%= "#{t('assignment.submission_grade.label.your_are_grading')} #{graded_rubric.submission_grade.assignment.display_name}" %></h4>

<%= form_for graded_rubric, url: preview_rubric_path, validate: true, method: :post do |form| %>
  <%= form.input :submission_grade_id, as: :hidden, value: graded_rubric.submission_grade_id %>
  <!-- Grading Criteria -->
  <table class="table table-bordered table-hover">
    <thead>
    <tr>
      <th>#</th>
      <th><%= t('assignment.submission_grade.label.weight') %></th>
      <th><%= t('assignment.submission_grade.label.criteria') %></th>
      <th style="width: 30%;"><%= t('assignment.submission_grade.label.meet_the_specification') %></th>
      <th style="width: 10%;"><%= t('assignment.submission_grade.label.point') %></th>
      <th style="width: 20%;"><%= t('assignment.submission_grade.label.comment') %></th>
      <th><%= t('assignment.submission_grade.label.mandatory') %></th>
    </tr>
    </thead>
    <tbody>
    <%= form.simple_fields_for :graded_criteriums do |criteria| %>
      <tr>
        <th><%= criteria.object.index %></th>
        <%= criteria.input :index, as: :hidden, value: criteria.object.index %>
        <td><span><%= criteria.object.weight %></span></td>
        <%= criteria.input :weight, as: :hidden, value: criteria.object.weight %>
        <%= criteria.input :mandatory, as: :hidden, value: criteria.object.mandatory %>
        <td>
          <span><%= criteria.object.criteria_description %></span>
          <%= criteria.input :criteria_description, as: :hidden, value: criteria.object.criteria_description %>
        </td>
        <td><span><%= criteria.object.meet_the_specification %></span></td>
        <%= criteria.input :meet_the_specification, as: :hidden, value: criteria.object.meet_the_specification %>
        <%= criteria.input :criteria_type, as: :hidden, value: criteria.object.criteria_type %>
        <td>
          <% if criteria.object.criteria_type == Constants::CRITERIA_TYPE_PASS_FAIL %>
            <%= criteria.input :status, :as => :select, validate: {:presence => true} %>
          <% else %>
            <%= criteria.input :point, collection: 0...(Settings[:criteria][:point_max_point] + 1),
                               validate: {:presence => true} %>
          <% end %>
        </td>
        <td><%= criteria.input :comment, as: :text, :label => false, :input_html => {:rows => 3},
                               validate: {:presence => true} %></td>
        <td><span><%= criteria.object.mandatory ? t('assignment.submission_grade.label.mandatory_yes') : t('assignment.submission_grade.label.mandatory_no') %></span></td>
        <%= criteria.input :mandatory, as: :hidden, value: criteria.object.mandatory %>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= form.input :comment, label: t('assignment.submission_grade.label.comment'), :input_html => {:rows => 3}, validate: {:presence => true} %>
  <%= form.button :submit, t('assignment.submission_grade.action.send_grade'), class: 'btn btn-primary btn-block' %>
<% end %>

app/views/graded_rubrics/form/_new2.html.erb
<%= form_for :submission, html: {:id => 'gradeForm'}, url: pre_caculate_grade_path, remote: true, method: :post do |form| %>
  <%= form.hidden_field :submission_grade_id, value: @submission_grade.id %>
  <!-- Grading Criteria -->
  <div class="form-group">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th><%= t('assignment.submission_grade.label.weight') %></th>
          <th style="width: 20%"><%= t('assignment.submission_grade.label.criteria') %></th>
          <th style="width: 30%"><%= t('assignment.submission_grade.label.meet_the_specification') %></th>
          <th><%= t('assignment.submission_grade.label.point') %></th>
          <th style="width: 10%"><%= t('assignment.submission_grade.label.comment') %></th>
          <th><%= t('assignment.submission_grade.label.mandatory') %></th>
        </tr>
      </thead>
      <tbody>
        <% @tobe_grade_criteria_formats.each do |cr| %>
          <tr>
            <th><%= cr.index %></th>
            <input name='cr[<%= cr.index %>][index]' type='hidden' value=<%= cr.index %> />
            <td><%= cr.weight %></td>
            <input name='cr[<%= cr.index %>][weight]' type='hidden' value=<%= cr.weight %> />
            <td><%= cr.criteria_description %></td>
            <textarea name='cr[<%= cr.index %>][desc]' class='display-none'><%= cr.criteria_description %> </textarea>
            <td><%= cr.meet_the_specification %></td>
            <textarea name='cr[<%= cr.index %>][spec]' class='display-none'><%= cr.meet_the_specification %> </textarea>
            <td><%= render :partial => 'graded_criteriums/point_input', :locals => {cr: cr} %></td>
            <td><textarea name='cr[<%= cr.index %>][note]' rows='3' required class='full-width__container br-radius-sm'></textarea></td>
            <td><%= render :partial => 'criteria_formats/mandatory', :locals => {mandatory: cr.mandatory} %></td>
            <input name='cr[<%= cr.index %>][mandatory]' type='hidden' value=<%= cr.mandatory %> />
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="form-group row">
    <label class="col-12"><%= t('assignment.submission_grade.label.comment') %></label>
    <div class="col-12">
      <%= form.text_area :comment, label: t('assignment.submission_grade.label.comment'), required: true, class: 'full-width__container br-radius-md', :input_html => {:rows => 3} %>
    </div>
  </div>
  <div class="form-group text-center">
    <%= form.submit t('assignment.submission_grade.action.send_grade'), id: 'btnSubmitGrade', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/graded_rubrics/form/_preview.html.erb
<%= form_for graded_rubric, url: :grade_rubric, method: :post do |form| %>

  <!--Area form showing confirm-->
  <div>
    <ul>
      <% graded_rubric.graded_criteriums.each do |criterium| %>
        <li><strong><%="#{t('assignment.submission_grade.label.criteria')} #{criterium.index}" %></strong>
          <% if criterium.mandatory %>
            <strong>(<%= t('assignment.submission_grade.label.mandatory_yes') %>) :</strong>
          <% else %>
            <strong> :</strong>
          <% end %>
          <% if criterium.criteria_type == Constants::CRITERIA_TYPE_PASS_FAIL %>
            <%= criterium.status %>
          <% else %>
            <%= criterium.point %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <p>
    <strong><%= t('assignment.submission_grade.label.total_point') %>: </strong>  <%= pre_calculate_point(graded_rubric) %>
  </p>
  <p>
    <strong><%= t('assignment.submission_grade.label.grade_status') %>: </strong> <%= pre_calculate_status(graded_rubric) %>
  </p>
  <hr>

  <!--    Hidden area-->
  <div hidden>
    <%= form.input :submission_grade_id, as: :hidden, value: graded_rubric.submission_grade_id %>
    <!-- Grading Criteria -->
    <table class="table table-bordered table-hover">
      <tbody>
      <%= form.fields_for :graded_criteriums do |criteria| %>
        <tr>
          <th><%= criteria.object.index %></th>
          <%= criteria.hidden_field :index, value: criteria.object.index %>
          <td><span><%= criteria.object.weight %></span></td>
          <%= criteria.hidden_field :weight, value: criteria.object.weight %>
          <%= criteria.hidden_field :mandatory, value: criteria.object.mandatory %>
          <td>
            <span><%= criteria.object.criteria_description %></span>
            <%= criteria.hidden_field :criteria_description, value: criteria.object.criteria_description %>
          </td>
          <td><span><%= criteria.object.outcome %></span></td>
          <%= criteria.hidden_field :outcome, value: criteria.object.outcome %>
          <td><span><%= criteria.object.meet_the_specification %></span></td>
          <%= criteria.hidden_field :meet_the_specification, value: criteria.object.meet_the_specification %>
          <%= criteria.hidden_field :criteria_type, value: criteria.object.criteria_type %>
          <td>
            <% if criteria.object.criteria_type == Constants::CRITERIA_TYPE_PASS_FAIL %>
              <%= criteria.hidden_field :status, value: criteria.object.status %>
            <% else %>
              <%= criteria.hidden_field :point, value: criteria.object.point %>
            <% end %>
          </td>
          <td><%= criteria.hidden_field :comment, :label => false, :input_html => {:rows => 3} %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= form.hidden_field :comment, :input_html => {:rows => 3} %>
  </div>

  <!--  Confirmation area-->
  <div>
    <%= link_to t('assignment.submission_grade.action.cancel'), :back, class: 'btn btn-danger' %>
    <%= form.button :submit, t('assignment.submission_grade.action.confirm'), class: 'btn btn-primary' %>

  </div>
<% end %>