config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  ActiveAdmin.routes(self)

  # Routes for ActiveAdmin
  namespace :admin do
    resources :courses do
      resources :course_instances
    end
    resources :programs do
      resources :course_instances
    end
    resources :course_instances do
      resources :assignments
      resources :enrollments
    end
    resources :assignments do
      resources :rubrics
    end
    resources :submission_grades do
      resources :graded_rubrics
    end
  end

  # Routes for submit and grade students' solution
  resources :submission_grades, only: %i[show index]
  resources :graded_rubrics, only: %i[new show]
  
  # Custom routes
  root to: 'home#index'
  get 'active_assignments', to: 'assignments#active_assignments'
  get 'assigned_submissions', to: 'submission_grades#assigned_submissions'
  get 'submit_solution', to: 'submission_grades#new_solution', as: :new_solution
  post 'submission_grades', to: 'submission_grades#create', as: :submit_solution
  post 'submission_grades/:id', to: 'submission_grades#report_invalid', as: :report_invalid_submission
  get 'grade_form', to: 'submission_grades#grade_form', as: :grade_form
  post 'pre_caculate_grade', to: 'submission_grades#pre_caculate_grade', as: :pre_caculate_grade
  post 'grade_submission', to: 'submission_grades#grade', as: :grade_submission
  get 'graded_rubrics/preview', to: 'graded_rubrics#preview_get', as: :get_preview_rubric
  post 'graded_rubrics/preview', to: 'graded_rubrics#preview', as: :preview_rubric
  post 'graded_rubrics/pre_caculate', to: 'graded_rubrics#pre_caculate', as: :pre_caculate_rubric
  post 'graded_rubrics', to: 'graded_rubrics#grade', as: :grade_rubric
  post 'import_enrollments', to: 'enrollments#import_enrollments', as: :import_enrollments
  post 'reset_results', to: 'enrollments#reset_results', as: :reset_results
end

app/views/shared/_assignments.html.erb
<h4><%= t('assignment.your_assignments') %></h4>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th><%= t('assignment.active.course') %></th>
    <th><%= t('assignment.active.assignment') %></th>
    <th><%= t('assignment.active.status') %></th>
    <th><%= t('assignment.active.action') %></th>
  </tr>
  </thead>
  <tbody>
  <% row_count = 0 %>
  <% assignments.each do |assignment| %>
    <% unless assignment.nil? %>
      <tr>
        <% row_count = row_count + 1 %>
        <th><%= row_count %></th>
        <td><%= assignment.course_instance.code %></td>
        <td><%= assignment.name %></td>
        <td><%= assignment.status_of_learner(current_user.id) %></td>
        <td>
          <% if student_can_submit?(assignment.id, current_user.id) %>
            <%= link_to t('assignment.submission_grade.action.submit_solution'), new_solution_path(:assignment_id => assignment.id) %>
            <% if assignment.status_of_learner(current_user.id) == Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED %>
              | <%= link_to t('assignment.submission_grade.action.view'), submission_grade_path(get_submission(assignment.id)) %>
            <% end %>
          <% else %>
            <%= link_to t('assignment.submission_grade.action.view'), submission_grade_path(get_submission(assignment.id)) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to image_tag('logofunix.png', :size => "80x50"), root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li>
          <p>
            <%= current_user.email %>
          </p>
        </li>
        <li class="ml-3">
          <%= link_to t('devise.sessions.logout_btn'), destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
        </li>
      <% else %>
        <%= link_to t('devise.sessions.login_btn'), new_user_session_path, class: 'btn btn-primary' %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice', 'success') %>
      toastr['<%= type %>'] ('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_submissions.html.erb
<div class="table table-hover table-responsive-sm" id="filterrific_results">
  <table>
    <thead>
    <tr>
      <th><%= t('assignment.active.status') %></th>
      <th><%= t('assignment.active.learner') %></th>
      <th><%= t('assignment.active.solution') %></th>
      <th><%= t('assignment.active.attempt') %></th>
      <th><%= t('assignment.submission_grade.label.assigned_at') %></th>
      <th><%= t('assignment.submission_grade.label.point') %></th>
      <th><%= t('assignment.submission_grade.label.note') %></th>
    </tr>
    </thead>
    <tbody>
    <% submissions.each do |submission| %>
      <%= render 'submission_grades/shared/submission', {submission: submission} %>
    <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate submissions %>