config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  ActiveAdmin.routes(self)

  # Routes for ActiveAdmin
  namespace :admin do
    resources :courses do
      resources :course_instances
    end
    resources :programs do
      resources :course_instances
    end
    resources :course_instances do
      resources :assignments
      resources :enrollments
    end
    resources :assignments do
      resources :rubrics
    end
    resources :submission_grades do
      resources :graded_rubrics
    end
  end

  # Routes for submit and grade students' solution
  resources :submission_grades, only: %i[show index]
  resources :graded_rubrics, only: %i[new show]
  
  # Custom routes
  root to: 'home#index'
  get 'active_assignments', to: 'assignments#active_assignments'
  get 'assigned_submissions', to: 'submission_grades#assigned_submissions'
  get 'submit_solution', to: 'submission_grades#new_solution', as: :new_solution
  post 'submission_grades', to: 'submission_grades#create', as: :submit_solution
  post 'submission_grades/:id', to: 'submission_grades#report_invalid', as: :report_invalid_submission
  get 'grade_form', to: 'submission_grades#grade_form', as: :grade_form
  post 'pre_caculate_grade', to: 'submission_grades#pre_caculate_grade', as: :pre_caculate_grade
  post 'grade_submission', to: 'submission_grades#grade', as: :grade_submission
  get 'graded_rubrics/preview', to: 'graded_rubrics#preview_get', as: :get_preview_rubric
  post 'graded_rubrics/preview', to: 'graded_rubrics#preview', as: :preview_rubric
  post 'graded_rubrics/pre_caculate', to: 'graded_rubrics#pre_caculate', as: :pre_caculate_rubric
  post 'graded_rubrics', to: 'graded_rubrics#grade', as: :grade_rubric
  post 'import_enrollments', to: 'enrollments#import_enrollments', as: :import_enrollments
  post 'reset_results', to: 'enrollments#reset_results', as: :reset_results
end

app/models/submission_grade.rb
# frozen_string_literal: true

class SubmissionGrade < ApplicationRecord
  acts_as_paranoid
  extend Enumerize
  include Constants

  after_save :set_submission_filename

  belongs_to :assignment, -> {with_deleted}
  belongs_to :student, class_name: 'User', foreign_key: 'student_id'
  belongs_to :mentor, class_name: 'User', foreign_key: 'mentor_id', optional: true
  has_one_attached :submission_file
  has_one_attached :graded_file

  has_one :course_instance, through: :assignment
  has_one :graded_rubric, dependent: :destroy

  has_many :graded_criteriums, through: :graded_rubric

  has_paper_trail on: %i[create update destroy]

  accepts_nested_attributes_for :graded_rubric

  enumerize :status, in: [Constants::SUBMISSION_GRADE_STATUS_SUBMITTED,
                          Constants::SUBMISSION_GRADE_STATUS_ASSIGNED,
                          Constants::SUBMISSION_GRADE_STATUS_TAKEN_BACK,
                          Constants::SUBMISSION_GRADE_STATUS_PASSED,
                          Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED]


  validates :submission_file, size: {less_than: 30.megabytes,
                                     message: 'file size is more than 30 MB'}
  # validate :validate_submission_file, on: :create

  def display_name
    "#{assignment.display_name} - Attempt #{attempt}"
  end

  scope :filtered_by_mentor_id, lambda {|mentor_id|
    where(mentor_id: mentor_id)
  }

  scope :sorted_by, lambda {|sort_option|
    direction = /desc$/.match?(sort_option) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^assigned_at_/
      order("submission_grades.assigned_at #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :with_status, lambda {|status|
    where(status: [*status])
  }

  def self.options_for_sorted_by
    [
        [I18n.t('assignment.submission_grade.list.assigned_date_newest_first'), 'assigned_at_desc'],
        [I18n.t('assignment.submission_grade.list.assigned_date_oldest_first'), 'assigned_at_asc']
    ]
  end

  def self.options_for_status
    {
        Constants::SUBMISSION_GRADE_STATUS_ASSIGNED => Constants::SUBMISSION_GRADE_STATUS_ASSIGNED,
        Constants::SUBMISSION_GRADE_STATUS_PASSED => Constants::SUBMISSION_GRADE_STATUS_PASSED,
        Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED => Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED
    }
  end

  def self.update_latest(student_id, assignment_id, attempt)
    begin
      prev_latest = SubmissionGrade.where(student_id: student_id,
                                          assignment_id: assignment_id,
                                          attempt: attempt).first
    rescue StandardError
      prev_latest = nil
    end
    unless prev_latest.nil?
      prev_latest.is_latest = false
      begin
        prev_latest.save
      rescue StandardError => error
        p error.inspect
      end
    end
  end

  def update_point(added_point)
    if attempt == 1
      self.point = added_point
    else
      prev = SubmissionGrade.where(student_id: student_id,
                                   assignment_id: assignment_id,
                                   attempt: attempt - 1).first
      self.point = prev.point + added_point
    end
  end

  def self.take_back
    to_taken_submissions = where('status = ? AND is_latest = ? AND assigned_at < ?',
                                 Constants::SUBMISSION_GRADE_STATUS_ASSIGNED,
                                 true,
                                 Time.now - Settings[:submission][:taken_back_after])

    to_taken_submissions.each do |submission|
      SubmissionGradeMailer.taken_back_email(submission.mentor_id, submission).deliver_later
      submission.update(status: Constants::SUBMISSION_GRADE_STATUS_TAKEN_BACK,
                        mentor_id: nil)
      # TODO
    end
  end

  def list_failed_criteria
    list_str = ''
    graded_criteriums.each do |criterium|
      if criterium.get_status == Constants::GRADED_CRITERIA_STATUS_FAILED
        list_str = list_str + ' ' + criterium.index.to_s + ','
      end
    end
    list_str
  end

  def assigned?
    status == Constants::SUBMISSION_GRADE_STATUS_ASSIGNED
  end
  
  def passed?
    status == Constants::SUBMISSION_GRADE_STATUS_PASSED
  end

  def not_passed?
    status == Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED
  end


  private
  def set_submission_filename
    if self.submission_file.attached?
      filename = self.assignment.display_name + '_' + self.student.email
      ext = '.' + self.submission_file.blob.filename.extension
      self.submission_file.blob.update(filename: filename+ext)
    end
  end
end

app/controllers/submission_grades_controller.rb
# frozen_string_literal: true

class SubmissionGradesController < ApplicationController
  include Constants
  include SubmissionGradesHelper
  include GradedCriteriumHelper

  before_action :set_submission_grade, only: %i[show update destroy]
  before_action :authorized_permission!, only: %i[show update destroy]
  before_action :authorized_admin!, only: %i[destroy index]
  before_action :authorized_granted!, only: [:assigned_submissions]
  after_action :attach_file, only: %i[create update]

  def report_invalid
    # TODO: Is going to implement
  end

  def create_solution
    # TODO: Is going to implement
  end

  def index
    @submission_grades = SubmissionGrade.where(is_latest: true)
  end

  def filter_submissions
  end

  def list_submissions
    respond_to :json, :html
    submissions = SubmissionGrade.where(mentor_id:current_user.id, is_latest:true).to_a
    @course_instances = Hash.new
    unless submissions.nil?
      submissions.each do |submission|
        course_instance = submission.assignment.course_instance
        @course_instances.merge!({course_instance.id => course_instance.code})
      end
    end
    @programs = {}
    unless @course_instances.nil?
      @course_instances.each do |course_instance_id, course_instance_code|
        program = CourseInstance.find(course_instance_id).program
        @programs.merge!({program.id => program.code})
      end
    end
    respond_to do |format|
      unless @programs.nil?
        format.html { render 'list_submissions'}
      end
    end
  end

  def assigned_submissions
    sg_service = SubmissionGradesService.new

    @submissions = sg_service.list_submissions params, current_user
    @status_report = sg_service.status_report current_user
  rescue Exception => e
    p e.inspect
    redirect_to root_path && return
  end

  def show
  end

  def new_solution
    if params[:assignment_id].present?
      assignment_id = params[:assignment_id]
      assignment = Assignment.find(assignment_id)
      @submission_grade = SubmissionGrade.new(assignment_id: assignment_id,
                                              status: Constants::SUBMISSION_GRADE_STATUS_SUBMITTED,
                                              student_id: current_user.id,
                                              is_latest: true)
      latest_submission = SubmissionGrade.find_by(assignment_id: assignment_id,
                                                  student_id: current_user.id,
                                                  is_latest: true)

      if latest_submission.nil? ||
          (latest_submission.status == Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED &&
           (assignment.max_attempt.zero? ? true :
            latest_submission.attempt < assignment.max_attempt))
      # Do nothing. Student can submit
      elsif latest_submission.status == Constants::SUBMISSION_GRADE_STATUS_PASSED
        flash[:success] = t('submission.latest_passed')
        redirect_to root_path
      else
        flash[:success] = t('submission.latest_being_processed')
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def create
    @submission_grade = SubmissionGrade.new(submission_grade_params)
    if student_can_submit?(@submission_grade.assignment_id, current_user.id)
      @submission_grade.attempt = find_attempt(@submission_grade.assignment_id, current_user.id)
      @submission_grade.grade_type = @submission_grade.assignment.grade_type
      respond_to do |format|
        if @submission_grade.save
          SubmissionGradeMailer.submitted_email(current_user, @submission_grade).deliver_later
          format.html {redirect_to active_assignments_path, success: 'Submission grade was successfully created.'}
          format.json {render :show, status: :created, location: @submission_grade}
        else
          format.html {render :new_solution}
          format.json {render json: @submission_grade.errors, status: :unprocessable_entity}
        end
        unless @submission_grade.attempt == 1
          SubmissionGrade.update_latest(@submission_grade.student_id, @submission_grade.assignment_id, @submission_grade.attempt - 1)
        end
      end
    else
      render js: "alert('You do not have permission to perform this action');"
    end
  end

  def destroy
    purge_file
    @submission_grade.destroy
    respond_to do |format|
      format.html {redirect_to submission_grades_url, notice: 'Submission grade was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def grade_form
    # Find parameters
    @submission_grade, @can_not_be_regrade_criteriums, @tobe_grade_criteria_formats = SubmissionGradesService.new.get_grade_form_params grade_params
    # Render the form
  end

  def pre_caculate_grade
    # binding.pry
    result = SubmissionGradesService.new.caculate_point_and_state(params)
    render 'confirm_grade', locals: {submission_id: params.permit(:submission_grade_id), comment: params.permit(:comment), cr_list: params.permit(:cr) , result: result}
  end

  def grade
    grade_result =  SubmissionGradesService.new.grade(params)
    if grade_result
      redirect_to submission_grade_path(params[:submission_id])
      flash[:success] = I18n.t('notification.grade_success')
    else
      redirect_to submission_grade_path(params[:submission_id])
      flash[:danger] = I18n.t('notification.grade_fail')
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_submission_grade
    @submission_grade = SubmissionGrade.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def submission_grade_params
    params.require(:submission_grade).permit(:assignment_id, :student_id, :status, :submission_file, :is_latest, :is_latest, :mentor_id, :graded_file, :point)
  end

  def attach_file
    unless @submission_grade.submission_file.attached?
      @submission_grade.submission_file.attach(params[:submission_file])
    end
    unless @submission_grade.graded_file.attached?
      @submission_grade.graded_file.attach(params[:graded_file])
    end
  end

  def purge_file
    @submission_grade.submission_file.purge
    @submission_grade.graded_file.purge
  end

  def authorized_admin!
    unless current_user.admin?
      flash.now[:danger] = 'You do not have permission to perform this action'
      redirect_to root_path
    end
  end

  def authorized_permission!
    if current_user.learner?
      if current_user.submission_grades.include?(@submission_grade)

      else
        flash.now[:danger] = 'You do not have permission to perform this action'
        redirect_to root_path
      end
    elsif current_user.admin?
      true
    elsif current_user.mentor?
      @submission_grade.mentor_id == current_user.id
    end
  end

  def authorized_granted!
    unless current_user.mentor? || current_user.admin?
      flash[:danger] = 'You do not have permission to take this action'
      redirect_to root_path
    end
  end

  def grade_params
    params.permit(:assignment_id, :student_id, :submission_grade_id)
  end
end

app/helpers/submission_grades_helper.rb
# frozen_string_literal: true

module SubmissionGradesHelper
  include Constants

  def status_css_class status
    if status == SUBMISSION_GRADE_STATUS_NOT_PASSED
      css_class = 'secondary'
    elsif status == SUBMISSION_GRADE_STATUS_ASSIGNED
      css_class = 'info'
    elsif status == SUBMISSION_GRADE_STATUS_PASSED
      css_class = 'success'
    end

    css_class
  end

  def status_lbl status
    if status == SUBMISSION_GRADE_STATUS_NOT_PASSED
      lbl = I18n.t('assignment.submission_grade.label.lbl_status_notpassed')
    elsif status == SUBMISSION_GRADE_STATUS_ASSIGNED
      lbl = I18n.t('assignment.submission_grade.label.lbl_status_assigned')
    elsif status == SUBMISSION_GRADE_STATUS_PASSED
      lbl = I18n.t('assignment.submission_grade.label.lbl_status_passed')
    end

    lbl
  end

  def student_can_submit?(assignment_id, user_id)
    last_submission_grade = SubmissionGrade.where(assignment_id: assignment_id, student_id: user_id, is_latest: true).first
    if last_submission_grade.nil? ||
        (last_submission_grade.status == Constants::SUBMISSION_GRADE_STATUS_NOT_PASSED &&
            (Assignment.find(assignment_id).max_attempt.zero? ? true : last_submission_grade.attempt < Assignment.find(assignment_id).max_attempt))
      true
    else
      false
    end
  end

  def find_attempt(assignment_id, user_id)
    sub_grade = SubmissionGrade.where(assignment_id: assignment_id, student_id: user_id, is_latest: true).first
    if sub_grade.nil?
      1
    else
      sub_grade.attempt + 1
    end
  end

  def list_graded_rubrics(submission_grade)
    submission_grades = SubmissionGrade.where(student_id: submission_grade.student_id, assignment_id: submission_grade.assignment_id)
    graded_rubrics = []
    if submission_grades.nil?
      nil
    else
      submission_grades.each do |submission|
        unless submission.graded_rubric.nil?
          graded_rubrics.append submission.graded_rubric
        end
      end
      graded_rubrics
    end
  end

  def count_assigned_submissions(course_instance_id, mentor_id)
    assignments = CourseInstance.find(course_instance_id).assignments
    count = 0
    unless assignments.nil?
      assignments.each do |assignment|
        count += SubmissionGrade.where(mentor_id: mentor_id, assignment_id: assignment.id, status: Constants::SUBMISSION_GRADE_STATUS_ASSIGNED).count
      end
    end
    count
  end

  def count_graded_submissions(course_instance_id, mentor_id)
    0
  end

  def need_interview?(submission_id)
    submission = SubmissionGrade.find(submission_id)
    if submission.grade_type == Constants::ASSIGNMENT_GRADE_TYPE_INTERVIEW
      need_review = true
      unless submission.nil? || submission.attempt == 1
        assignment_id = submission.assignment_id
        student_id = submission.student_id
        submissions = SubmissionGrade.where(assignment_id: assignment_id, student_id: student_id).to_a
        unless submissions.blank?
          submissions.each do |submission|
            if !submission.point.nil? && submission.point != 0
              need_review = false
              break
            end
          end
        end
      end
      need_review
    else
      false
    end

  end
end

app/views/submission_grades/_confirmation_modal.html.erb
<div class="modal fade show" id="confirmation-modal" style="display: none; padding-right: 12px;" aria-modal="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= t('assignment.submission_grade.action.confirm_grade') %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body" id='confirmation-modal-body'>
        <p>Loading</p>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

app/views/submission_grades/_confirmation_modal_body.html.erb
<%= form_with(url: grade_submission_path, id: 'confirmSendGradeForm', local: true, method: :post) do |form| %>
  <%= form.hidden_field :submission_id, value: result[:submission_id] %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th><%= t('assignment.submission_grade.label.weight') %></th>
        <th style="width: 30%;"><%= t('assignment.submission_grade.label.meet_the_specification') %></th>
        <th><%= t('assignment.submission_grade.label.point') %></th>
        <th style="width: 20%;"><%= t('assignment.submission_grade.label.comment') %></th>
        <th><%= t('assignment.submission_grade.label.mandatory') %></th>
      </tr>
    </thead>
    <tbody>
      <% result[:cr_list].each do |criteria| %>
        <tr>
          <input name='cr[<%= criteria[:index] %>][index]' type='hidden' value=<%= criteria[:index] %> />
          <input name='cr[<%= criteria[:index] %>][weight]' type='hidden' value=<%= criteria[:weight] %> />
          <textarea name='cr[<%= criteria[:index] %>][desc]' class='display-none'><%= criteria[:desc] %> </textarea>
          <textarea name='cr[<%= criteria[:index] %>][spec]' class='display-none'><%= criteria[:spec] %> </textarea>
          <textarea name='cr[<%= criteria[:index] %>][note]' class='display-none'><%= criteria[:note] %></textarea>
          <input name='cr[<%= criteria[:index] %>][mandatory]' type='hidden' value=<%= criteria[:mandatory] %> />
          <th><%= criteria[:index] %></th>
          <td><span><%= criteria[:weight] %></span></td>
          <td><span><%= criteria[:spec] %></span></td>
          <td>
            <%= render :partial => "graded_criteriums/status_with_hidden_input", :locals => {cr_index: criteria[:index], cr_type: criteria[:criteria_type], cr_status: criteria[:pointfp], cr_point: criteria[:pointp]} %>
          </td>
          <td><span><%= criteria[:note] %></span></td>
          <td>
            <%= render :partial => "graded_criteriums/mandatory", :locals => {mandatory: criteria[:mandatory]} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr/>
  <div class='row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.submission_grade.label.note') %></label>
    <div class="col-sm-10 col-form-label">
      <p class="mg-auto">
      <div>
        <%= result[:comment] %>
      </div>
      </p>
      <textarea name='note' class='display-none'><%= result[:comment] %></textarea>
    </div>
  </div>
  <div class='row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.status') %></label>
    <div class="col-sm-10 col-form-label">
      <p class="mg-auto"><%= render :partial => 'submission_grades/shared/status', :locals => {status: result[:status], full_width: false} %></p>
    </div>
  </div>
  <div class='row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.point') %>:</label>
    <div class="col-sm-10 col-form-label">
      <p class="mg-auto"><%= result[:point] %></p>
    </div>
  </div>
  <div class="modal-footer justify-content-between">
    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('assignment.submission_grade.action.close') %></button>
    <%= form.submit t('assignment.submission_grade.action.confirm_grade'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/submission_grades/_filter.html.erb
<div class="row">
  
</div>

app/views/submission_grades/_formsubmitnew.html.erb
<%= simple_form_for submission_grade do |form| %>

  <!--  Area for showing error if have any-->
  <% if submission_grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission_grade.errors.count, "error") %> prohibited this submission_grade from being
        saved:</h2>

      <ul>
        <% submission_grade.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--  Hidden area-->
  <div hidden>
    <%= form.input :assignment_id %>
    <%= form.input :student_id %>
    <%= form.input :status %>
    <%= form.input :is_latest %>
    <%= form.input :point %>
  </div>

  <!--  Input area-->
  <table>
    <tbody>
    <tr>
      <th><%= t('assignment.active.assignment') %></th>
      <td><%= submission_grade.assignment.display_name %></td>
    </tr>
    <tr>
      <th><%= t('assignment.active.learner') %></th>
      <td><%= current_user.email %></td>
    </tr>
    <% if submission_grade.assignment.submit_type != Constants::ASSIGNMENT_SUBMIT_TYPE_NOFILE %>
      <tr>
        <th><%= t('attachment.action.attach_file') %></th>
        <td><%= form.file_field :submission_file, as: :file, label: false, required: true %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= link_to t('assignment.submission_grade.action.cancel'), active_assignments_path, class: 'btn btn-danger' %>
    <%= form.button :submit,  submission_grade.assignment.submit_type != Constants::ASSIGNMENT_SUBMIT_TYPE_NOFILE ? t('assignment.submission_grade.action.submit_solution') : t('assignment.submission_grade.action.ready_interview'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/submission_grades/_status_report_item.html.erb
<a href="<%= assigned_submissions_path(status: status) %> " class="btn btn-<%= status_css_class(status) %>"><%= status_lbl(status) %> <span class="badge badge-light"><%= count %></span></a>

app/views/submission_grades/_submission_actions.html.erb
<% if current_user.mentor? || current_user.admin? %>
  <% if @submission_grade.status == Constants::SUBMISSION_GRADE_STATUS_ASSIGNED %>
    <%= link_to "<i class='fas fa-marker'></i>&nbsp;#{t('assignment.submission_grade.action.grade')}</button>".html_safe, grade_form_path(assignment_id: @submission_grade.assignment_id,student_id: @submission_grade.student_id,submission_grade_id: @submission_grade.id), class: 'btn btn-sm btn-primary' %>
  <% end %>
<% end %>

<% if current_user.learner? %>
  <% list_graded_rubrics = list_graded_rubrics(@submission_grade) %>
  <% if list_graded_rubrics.any? %>
    <h4><%= t('assignment.submission_grade.list.history_of_grades') %></h4>
    <%= render partial: 'graded_rubrics/list_embedded_show', locals: {graded_rubrics: list_graded_rubrics} %>
  <% end %>
<% end %>

app/views/submission_grades/_submission_div.html.erb
<% sg_decorated = SubmissionGradeDecorator.new(submission) %>
<div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.assignment') %></label>
    <div class="col-sm-10">
      <p class="mg-auto"><%= submission.assignment.name %></p>
    </div>
  </div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.course') %></label>
    <div class="col-sm-10">
      <p class="mg-auto"><%= submission.assignment.course_instance.code %></p>
    </div>
  </div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.learner') %></label>
    <div class="col-sm-10">
      <p class="mg-auto"><%= submission.student.email %></p>
    </div>
  </div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.status') %></label>
    <div class="col-sm-10">
      <p class="mg-auto"><%= render :partial => 'submission_grades/shared/status', :locals => {status: submission.status, full_width: false} %></p>
    </div>
  </div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label">
      <%= t('assignment.active.solution') %></label>
    <div class="col-sm-10">
      <p class="mg-auto">
      <%= render :partial => 'submission_grades/shared/submission_file', :locals => {submission: submission} %>
      </p>
    </div>
  </div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.attempt') %></label>
    <div class="col-sm-10"><p class="mg-auto"><%= submission.attempt %></p></div>
  </div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.mentor') %></label>
    <div class="col-sm-10">
      <p class="mg-auto">
      <%= submission.mentor&.email %>
      </p>
    </div>
  </div>
  <div class='form-group row'>
    <label class="col-sm-2 col-form-label"><%= t('assignment.active.point') %>:</label>
    <div class="col-sm-10">
      <p class="mg-auto"><%= sg_decorated.point_frm %></p>
    </div>
  </div>
</div>

app/views/submission_grades/grade_form.html.erb
<% content_for :stylesheet_includes do %>
  <%= stylesheet_link_tag 'graded_rubrics' %>
<% end %>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'submission_grades' %>
<% end %>

<%= link_to "<i class='fas fa-arrow-left'></i>&nbsp;#{t('assignment.submission_grade.action.back')}".html_safe, assigned_submissions_path %>

<h3><%= "#{t('assignment.submission_grade.label.your_are_grading')} #{@submission_grade.assignment.display_name}" %></h3>

<div class="card card-outline card-primary">
  <div class="card-body">
    <%= render :partial => 'submission_grades/submission_div_simple', :locals => {submission: @submission_grade} %>
  </div>
</div>
<% unless @can_not_be_regrade_criteriums.size.zero? %>
  <div class="card card-outline card-primary">
    <div class="card-header">
      <h3 class="card-title"><%= t('assignment.submission_grade.label.previous_graded_criteria') %></h3>
    </div>
    <div class="card-body">
      <%= render :partial => 'graded_rubrics/form/graded', locals: {can_not_be_regrade_criteriums: @can_not_be_regrade_criteriums} %>
    </div>
  </div>
<% end %>
<div class="card card-outline card-primary">
  <div class="card-header">
    <h3 class="card-title"><%= "#{t('assignment.submission_grade.label.to_grade_criteria')}" %></h3>
  </div>
  <div class="card-body">
    <%= render :partial =>  'graded_rubrics/form/new2', locals: {graded_rubric: @graded_rubric} %>
  </div>
</div>

<%= link_to "<i class='fas fa-arrow-left'></i>&nbsp;#{t('assignment.submission_grade.action.back')}".html_safe, assigned_submissions_path %>

<%= render 'confirmation_modal' %>

app/views/submission_grades/show.html.erb
<div class="card">
  <div class="card-header">
    <%= link_to "<i class='fas fa-arrow-left'></i>&nbsp;#{t('assignment.submission_grade.action.back')}".html_safe, current_user.learner? ? active_assignments_path : assigned_submissions_path %>
  </div>
  <div class="card-body">
    <%= render :partial => "submission_div", :locals => {submission: @submission_grade} %>
  </div>
  <div class="card-footer">
    <%= render "submission_actions" %>
  </div>
</div>